---
name: Go version setup
permissions: read-all

on:
  workflow_call:
    outputs:
      goversion:
        value: ${{ jobs.version.outputs.goversion }}

jobs:
  version:
    name: Set Go version variable for all the workflows
    runs-on: ubuntu-latest
    outputs:
      goversion: ${{ steps.goversion.outputs.goversion }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - id: goversion
        run: |
          GO_VERSION=$(cat .go-version)
          echo "Go Version: $GO_VERSION"
          echo "goversion=$GO_VERSION" >> $GITHUB_OUTPUT
